### ISSUE TITLE
Repositioning the direction of the community version of Redash.

### ISSUE THREAD

**Issue by Avey777** [RedashCommunity/redash#13]
Currently, RedashCommunity/redash occasionally updates with minor changes. I believe that RedashCommunity/redash should be repositioned. The community version of Redash should have a clear direction, whether it is to develop independently or to be compatible with the original Redash.

**Comment by justinclift** [comment]
> ... whether it is to develop independently or to be compatible with the original Redash.

My thinking here is that we should provide a home for people who need to keep on using the public / Community version of Redash, as the original upstream project seems to be dead now. :frowning:

Once we have the initial builds working "ok", we can then develop things however people seem fit.  We'll need to make sure there's a clear upgrade path for people on the original Redash releases though, as that's likely a common starting point.
