### ISSUE TITLE
Switching data sources through variables

### ISSUE THREAD

**Issue by Avey777** [RedashCommunity/redash#32]
"Sometimes, it is inevitable that the data in the same format is distributed across different machine instances. In this case, it would be a great solution if we can choose the data source we want to connect to through URL variables. This can achieve a more flexible data source selection and allow the BI application to dynamically load different data source configurations based on the value of the variables at runtime.

Of course, this is just an option and can be used only by those who need it."

eg：
`https://redash.amiemall.com/source_base = {{source_name}}/dashboards/2--?p_country=CN`

### **source_base = {{source_name}}**

**Comment by justinclift** [comment]
Where are you thinking these variables would be defined, and stored? :smile:

Are you thinking of (for example) inside the `env` environment file, or are you meaning they should be defined through the Redash web interface *somewhere*, or something else?

**Comment by Avey777** [comment]
> Where are you thinking these variables would be defined, and stored? 😄
> 
> Are you thinking of (for example) inside the environment file, or are you meaning they should be defined through the Redash web interface _somewhere_, or something else?`env`

You can pass in the data source to be linked through the shared URL.

**Comment by Avey777** [comment]
Data merge
```
req1 ={
    'ds':'Tospino-test',
    'sql':'select  username as uname , password as pw from test.demo'
}
req2 ={
    'ds':'Tospino-test',
    'sql':'select  username as uname , password as pw from test.demo'
}

req3 ={
    'ds':'Tospino-test',
    'sql':'select  username as uname , password as pw from test.demo'
}

def merge_data(*args):
    import pandas as pd
    res_list = []
    for req in args:
        try:
            res = execute_query(req['ds'],req['sql'])
        except:
            print('请求异常')
            return {'columns':[],'rows':[]}
        res_list.append(res['rows'])
    res_df_list = [ pd.DataFrame(res) for res in res_list ]
    merge_df = pd.concat(res_df_list)
    rows = merge_df.to_dict(orient='records')
    cols_list = merge_df.columns.tolist()
    cols = [{'name':col,"type": "string", "friendly_name": col} for col in cols_list]
    return {'columns':cols,'rows':rows}

result = merge_data(req1,req2,req3)
