### ISSUE TITLE
"Documentation on the Python and Node.js environments corresponding to the source code."

### ISSUE THREAD

**Issue by Avey777** [RedashCommunity/redash#37]
"I hope to specify the required versions of Python and Node.js in the requirements.txt file or a separate file, so that it won't feel messy when debugging with source code."

**Comment by gaecoli** [comment]
> "I hope to specify the required versions of Python and Node.js in the requirements.txt file or a separate file, so that it won't feel messy when debugging with source code."

`
Python: 3.7~3.10
Node: >= 12
`

**Comment by Avey777** [comment]
> > "I hope to specify the required versions of Python and Node.js in the requirements.txt file or a separate file, so that it won't feel messy when debugging with source code."
> 
> `Python: 3.7~3.10 Node: >= 12`


Python 3.9+" is not compatible with the default dependency packages, so I found a tutorial from another company. Similar tutorials happen to be what our open-source community lacks.


https://redash.dazdata.com/docs/opensource/opensouce_install/installer_introduce/

**Comment by justinclift** [comment]
Interesting, that seems useful.  Google Translate seems to do a reasonable job of that page too. :smile:

**Comment by justinclift** [comment]
@Avey777 Any idea what https://pan.baidu.com is?  I can't connect to that server.  Might be because I'm in Australia?

**Comment by Avey777** [comment]
> @Avey777 Any idea what https://pan.baidu.com is? I can't connect to that server. Might be because I'm in Australia?

Is this something like Google Drive, and do you need to download anything from it? If you need it, you can send me the link and I can help you download it.

**Comment by justinclift** [comment]
Cool.  On [this page](https://redash.dazdata.com/docs/enterprise/change_log/91) they seem to have "update packages" for their version of Redash.  I was thinking to grab a few and pull them apart to see what's in them.  Mainly from curiosity. :smile:

**Comment by Avey777** [comment]
> Cool. On [this page](https://redash.dazdata.com/docs/enterprise/change_log/91) they seem to have "update packages" for their version of Redash. I was thinking to grab a few and pull them apart to see what's in them. Mainly from curiosity. 😄
How can I send it to you? Do we have communication communities such as Slack or Skype?

**Comment by justinclift** [comment]
How big is the file? :smile:

**Comment by Avey777** [comment]
> How big is the file? 😄

You can try it: https://flowus.cn/share/7a6f3ec2-eef6-49ba-b690-cf9744aa5cba

**Comment by justinclift** [comment]
Thanks @Avey777, that download worked.  I haven't taken it apart yet, but should sometime in the next few days. :smile:

**Comment by Avey777** [comment]
The following requirements.txt dependencies support >= python3.10.0. If anyone wants to make significant upgrades to Python dependencies, this can serve as a reference.

```
#Flask==1.1.1
Flask==2.2.5
#Jinja2==2.10.3
Jinja2==3.0.0
#itsdangerous==1.1.0
itsdangerous==2.0.0
#click==6.7
click==8.0
#MarkupSafe==1.1.1
MarkupSafe==2.1.1
pyOpenSSL==19.0.0
httplib2==0.14.0
wtforms==2.2.1
Flask-RESTful==0.3.7
Flask-Login==0.4.1
Flask-SQLAlchemy==2.4.1
Flask-Migrate==2.5.2
flask-mail==0.9.1
flask-talisman==0.7.0
Flask-Limiter==0.9.3
Flask-WTF==0.14.3
passlib==1.7.1
aniso8601==8.0.0
blinker==1.4
#psycopg2 depend apt install libpq-dev
#psycopg2==2.8.3
psycopg2==2.9.1
python-dateutil==2.8.0
pytz>=2019.3
PyYAML==5.4
redis==4.4.4
requests==2.31.0
SQLAlchemy==1.3.10
# We can't upgrade SQLAlchemy-Searchable version as newer versions require PostgreSQL > 9.6, but we target older versions at the moment.
SQLAlchemy-Searchable==0.10.6
# We need to pin the version of pyparsing, as newer versions break SQLAlchemy-Searchable-10.0.6 (newer versions no longer depend on it)
pyparsing==2.3.0
#SQLAlchemy-Utils==0.34.2
SQLAlchemy-Utils==0.37.9
sqlparse==0.3.0
statsd==3.3.0
#greenlet==0.4.16
greenlet==1.1.3
gunicorn==20.0.4
rq==1.5.0
rq-scheduler==0.9.1
jsonschema==3.1.1
RestrictedPython==5.0
pysaml2==6.5.2
pycrypto==2.6.1
python-dotenv==0.19.2
funcy==1.13
sentry-sdk>=0.14.3,<0.15.0
semver==2.8.1
xlsxwriter==1.2.2
pystache==0.6.0
parsedatetime==2.4
PyJWT==1.7.1
#cryptography==2.8
cryptography==41.0.0
simplejson==3.16.0
ua-parser==0.8.0
user-agents==2.0
maxminddb-geolite2==2018.703
pypd==1.1.0
disposable-email-domains>=0.0.52
#gevent==1.4.0
gevent==22.8.0
sshtunnel==0.1.5
supervisor==4.1.0
supervisor_checks==0.8.1
#werkzeug==0.16.1
werkzeug==2.2.3
# Uncomment the requirement for ldap3 if using ldap.
# It is not included by default because of the GPL license conflict.
# ldap3==2.2.4
Authlib==0.15.5
advocate==1.0.0


----------

**Comment by justinclift** [comment]
Are you saying it *doesn't* support Python 3.8 for sure, or are you saying you've only tested it on Python 3.10 so that's what you know works? :smile:

**Comment by Avey777** [comment]
> Are you saying it _doesn't_ support Python 3.8 for sure, or are you saying you've only tested it on Python 3.10 so that's what you know works? 😄

I have tried it on version 3.9.2, 3.10.0, and 3.11.2, and only 3.10.0 and 3.11.2 are feasible. However, we definitely need to modify some source code to make Redash work properly (this is something that someone needs to do).

**Comment by Avey777** [comment]
> > "I hope to specify the required versions of Python and Node.js in the requirements.txt file or a separate file, so that it won't feel messy when debugging with source code."
> 
> `Python: 3.7~3.10 Node: >= 12`

Node.js version 18 has some issues during compilation, so we are not able to use this version yet.
