### ISSUE TITLE
Use pycryptodome instead of pycrypto

### ISSUE THREAD

**Issue by Avey777** [RedashCommunity/redash#66]
It's time to consider replacing pycrypto, and I recommend using pycryptodome. Now we can start discussing.

```
requirements.txt
pycrypto==2.6.1
```
```>>>>```

```
requirements.txt
pycryptodome==3.18.0
```

```-------------```

[pycryptodome](https://github.com/Legrandin/pycryptodome)

**Comment by justinclift** [comment]
What's the benefit for changing to pycryptodome? :smile:

**Comment by Avey777** [comment]
> What's the benefit for changing to pycryptodome? 😄
> 
> Oh, I was misreading the Release history page for pycrypto. It's last release was in 2013, so nearly 10 years ago.
> 
> On that basis alone, I reckon you're right @Avey777. 😄

Substituting pycryptodome==3.18.0 for pycrypto==2.6.1 locally, all my data runs normally without modifying the source code. However, it currently cannot pass our test suite, so a small modification may be needed in the code.

**Comment by justinclift** [comment]
Yeah.  It'll probably need someone to investigate it and fix whatever the problem is.

**Comment by Avey777** [comment]
I found that redash is already using cryptography==2.8. So, is it still necessary to continue using pycryptodome? Someone needs to look into this matter.
-----------------------------
https://www.pycrypto.org/
![image](https://github.com/RedashCommunity/redash/assets/35259040/03282210-1af3-4756-86c1-ea75904a55c0)

**Comment by Avey777** [comment]
@justinclift 
I have searched the entire project and haven't found any usage of the pycrypto dependency other than in the requirements.txt file. Can I try removing this dependency?

**Comment by justinclift** [comment]
Sure, try it out. :smile:
